dynamixel_state:
  type: joint_state_controller/JointStateController
  publish_rate: 100


dynamixel_control:
  type: pos_vel_controllers/JointTrajectoryController
  # state_publish_rate: 50
  # action_monitor_rate: 20
  # stop_trajectory_duration: 0.0
  allow_partial_joints_goal: True
  joints: [head_p, head_y, 
           l_sho_p, l_sho_r, l_elb_y, l_elb_p,
           r_sho_p, r_sho_r, r_elb_y, r_elb_p,
           l_hip_r, l_hip_p, l_kne_p, l_kne_y, l_ank_p, l_ank_r,
           r_hip_r, r_hip_p, r_kne_p, r_kne_y, r_ank_p, r_ank_r]
  constrains:
    # stopped_velocity_tolerance: 0.01
    goal_time: 1.0
    # <joint>:
    #   goal: 0.0
    #   trajectory: 0.0


communication_statistics:
  type: mh5_controllers/CommunicationStatsController
  publish_period: 10.0

torque_control:
  type: mh5_controllers/ActiveJointController
  groups: [head, left_arm, right_arm, arms, left_leg, right_leg, legs, all]
  head: [head_p, head_y]
  left_arm: [l_sho_p, l_sho_r, l_elb_y, l_elb_p]
  right_arm: [r_sho_p, r_sho_r, r_elb_y, r_elb_p]
  arms: [left_arm, right_arm]
  left_leg: [l_hip_r, l_hip_p, l_kne_p, l_kne_y, l_ank_p, l_ank_r]
  right_leg: [r_hip_r, r_hip_p, r_kne_p, r_kne_y, r_ank_p, r_ank_r]
  legs: [left_leg, right_leg]
  all: [head, arms, legs]

imu_state:
  type: imu_sensor_controller/ImuSensorController
  publish_rate: 100
