upper_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - head_p
    - head_y

lower_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - l_hip_p
    - l_hip_r
    - l_kne_p
    - l_kne_y
    - l_ank_p
    - l_ank_r
    - r_hip_p
    - r_hip_r
    - r_kne_p
    - r_kne_y
    - r_ank_p
    - r_ank_r    

/gazebo_ros_control:   
  pid_gains:
    head_p: {p: 2.0, i: 0.0, d: 0.0}
    head_y: {p: 2.0, i: 0.0, d: 0.0}
    l_hip_p: {p: 2.0, i: 0.0, d: 0.0}
    l_hip_r: {p: 2.0, i: 0.0, d: 0.0}
    l_kne_p: {p: 2.0, i: 0.0, d: 0.0}
    l_kne_y: {p: 2.0, i: 0.0, d: 0.0}
    l_ank_p: {p: 2.0, i: 0.0, d: 0.0}
    l_ank_r: {p: 2.0, i: 0.0, d: 0.0}
    r_hip_p: {p: 2.0, i: 0.0, d: 0.0}
    r_hip_r: {p: 2.0, i: 0.0, d: 0.0}
    r_kne_p: {p: 2.0, i: 0.0, d: 0.0}
    r_kne_y: {p: 2.0, i: 0.0, d: 0.0}
    r_ank_p: {p: 2.0, i: 0.0, d: 0.0}
    r_ank_r: {p: 2.0, i: 0.0, d: 0.0}
