robot_hardware:
  - upper_body
  - lower_body
upper_body:
  type: mh5_hardware_interface/MH5DynamixelInterface
  joints:
    - head_p
    - head_y
  port: /dev/ttySC0
  baudrate: 2000000
  protocol: 2.0
  rs485: true
  mr1_joint1:
    id: 11
    pid: [100, 0, 4000]
    profile: [0, 0]
lower_body:
  type: mh5_hardware_interface/MH5DynamixelInterface
  port: /dev/ttySC1
  baudrate: 2000000
  protocol: 2.0
  joints:
    - l_hip_r
    - l_hip_p